### ISSUE TITLE
Request builder create NS for array instead L.

### ISSUE THREAD

**Issue by chyzwar** [Giftbit/dynameh#11]
Hi, 

Order of items in NumberSet is not guaranteed. Dynameh should only use Set types if instance of JavaScript Set is passed. 

This part of code is problematic: 
```js
          if (firstItemType === "number" && item.every(x => typeof x === "number")) {
                        return {NS: item.map(n => n.toString())};
                    }
```

I think for other array "L" type should be used as well.

**Comment by pushplay** [comment]
Resolved in https://github.com/Giftbit/dynameh/pull/12 .
