### ISSUE TITLE
Number converter does not work with 0

### ISSUE THREAD

**Issue by ruhkopf** [Giftbit/dynameh#9]
The [responseUnwrapper](https://github.com/Giftbit/dynameh/blob/master/src/responseUnwrapper.ts#L26) does not work with items with a numerical value of 0, e.g:
```
"Item": {
  "v": { "N": 0 }
}
```
This causes the following error:
```
Unhandled response item {
  "N": 0
}
```
Suggest to replace `else if (item.N) {` with `else if (item.hasOwnProperty("N"))`

**Comment by pushplay** [comment]
Hi @ruhkopf ,

I'm not sure that's a valid response.  According to [this document](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes)...

> All numbers are sent across the network to DynamoDB as strings, to maximize compatibility across languages and libraries.

Thus the response should contain:

```json
"Item": {
  "v": { "N": "0" }
}
```

Dynemeh could be relaxed to be more forgiving there.  How did you generate that response?

**Comment by ruhkopf** [comment]
Hi @pushplay,
Ah yes, you are right. I used this invalid test fixture in one of my unit tests. I've fixed the test accordingly. Thanks a lot for your quick response!

**Comment by pushplay** [comment]
No worries.  Maybe I'll add checks and warnings for invalid data types like that.
